export const GET_ALL_JOBS_REQUEST = 'GET_ALL_JOBS_REQUEST';
export const GET_ALL_JOBS_SUCCESS = 'GET_ALL_JOBS_SUCCESS';
export const GET_ALL_JOBS_FAIL = 'GET_ALL_JOBS_FAIL';

export const JOB_SEARCH_BY_KEYWORD_REQUEST = 'JOB_SEARCH_BY_KEYWORD_REQUEST';
export const JOB_SEARCH_BY_KEYWORD_SUCCESS = 'JOB_SEARCH_BY_KEYWORD_SUCCESS';
export const JOB_SEARCH_BY_KEYWORD_FAIL = 'JOB_SEARCH_BY_KEYWORD_FAIL';

export const GET_JOBS_BY_LOCATION_REQUEST = 'GET_JOBS_BY_LOCATION_REQUEST';
export const GET_JOBS_BY_LOCATION_SUCCESS = 'GET_JOBS_BY_LOCATION_SUCCESS';
export const GET_JOBS_BY_LOCATION_FAIL = 'GET_JOBS_BY_LOCATION_FAIL';
